# Generated by Django 5.2.13 on 2026-04-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_redesocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('produtos', 'Produtos'), ('texto', 'Texto'), ('texto_imagem', 'Texto com imagem'), ('chamada', 'Chamada para ação')], default='produtos', max_length=30)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=300, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='secoes/')),
                ('botao_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('botao_link', models.CharField(blank=True, max_length=300, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produtos', models.ManyToManyField(blank=True, related_name='secoes_home', to='core.produto')),
            ],
            options={
                'verbose_name': 'Seção da Home',
                'verbose_name_plural': 'Seções da Home',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='RedeSocial',
        ),
    ]
